# Generated by Django 4.0.1 on 2022-03-29 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchs',
            name='team1_id',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='team2_id',
        ),
    ]
