# Generated by Django 4.0.1 on 2022-03-29 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_matchs_team1_id_remove_matchs_team2_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='matchs',
        ),
    ]
