# Generated by Django 4.0.1 on 2022-04-08 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('player', '0004_player_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='invitation',
            fields=[
                ('player_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('coplayer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coplayer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
