# Generated by Django 4.0.1 on 2022-04-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
