# Generated by Django 4.0.1 on 2022-04-19 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0006_invitation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='captain',
        ),
        migrations.AddField(
            model_name='team',
            name='captain_id',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
