# Generated by Django 4.0.1 on 2022-04-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_remove_player_captain_team_captain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='no_of_matchs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_score',
            field=models.IntegerField(default=0),
        ),
    ]
