# Generated by Django 4.0.1 on 2022-04-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_alter_player_no_of_matchs_alter_player_player_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_email',
        ),
    ]
