# Generated by Django 4.0.1 on 2022-03-29 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0003_delete_matchs'),
        ('player', '0004_player_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='matchs',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(unique=True)),
                ('team1_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team1', to='player.team')),
                ('team2_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='player.team')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tournament.tournament')),
            ],
        ),
    ]
