# Generated by Django 4.0.1 on 2022-03-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchs',
            name='date_time',
            field=models.DateField(unique=True),
        ),
    ]
