# Generated by Django 4.0.1 on 2022-03-29 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='organiser',
            fields=[
                ('organiser_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organiser_name', models.CharField(max_length=20)),
                ('organiser_email', models.EmailField(default='email@email.com', max_length=254, unique=True)),
            ],
        ),
    ]
