# Generated by Django 4.0.1 on 2022-04-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creater', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organiser',
            name='organiser_email',
        ),
        migrations.RemoveField(
            model_name='organiser',
            name='organiser_name',
        ),
    ]
